[build]
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20" 
  NPM_FLAGS = "--legacy-peer-deps"
  publish = ".next"
